trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c Release -o $(Build.StagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Copy to Azure Pipelines
  inputs:
    PathtoPublish: '$(Build.StagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'